<script setup lang="ts">
import { ChatContainer } from "~/components/Chat";
import type { Message, Thread, FileAttachment } from "~/components/Chat/types";

// Demo state
const messages = ref<Message[]>([]);

const isLoading = ref(false);
const currentThread = ref<Thread>({
  id: "demo-thread",
  title: "Nuxt 3 Data Fetching",
  createdAt: new Date(Date.now() - 6 * 60 * 1000),
  updatedAt: new Date(),
  messages: [],
});

// Event handlers
const handleMessageSubmit = async (
  content: string,
  attachments?: FileAttachment[]
) => {
  // Add user message
  const userMessage: Message = {
    id: `user-${Date.now()}`,
    role: "user",
    content,
    timestamp: new Date(),
    attachments,
  };
  messages.value.push(userMessage);

  // Simulate AI response
  isLoading.value = true;

  setTimeout(() => {
    const aiMessage: Message = {
      id: `ai-${Date.now()}`,
      role: "assistant",
      content: `Thanks for your question: "${content}"\n\nThis is a demo response. In a real implementation, this would be generated by your AI model based on your knowledge base and context.`,
      timestamp: new Date(),
      metadata: {
        model: "demo-model",
        tokenUsage: {
          prompt: content.length,
          completion: 150,
          total: content.length + 150,
        },
      },
    };

    messages.value.push(aiMessage);
    isLoading.value = false;
  }, 2000);
};

const handleMessageCopy = (content: string) => {
  navigator.clipboard.writeText(content);
  // You could add a toast notification here
  console.log("Message copied to clipboard");
};

const handleMessageEdit = (messageId: string) => {
  console.log("Edit message:", messageId);
  // Implement edit functionality
};

const handleMessageDelete = (messageId: string) => {
  const index = messages.value.findIndex((m) => m.id === messageId);
  if (index !== -1) {
    messages.value.splice(index, 1);
  }
};

const handleMessageRegenerate = (messageId: string) => {
  console.log("Regenerate message:", messageId);
  // Implement regenerate functionality
};

const handleSourceClick = (source: any) => {
  window.open(source.url, "_blank");
};

const handleThreadSelect = (threadId: string) => {
  console.log("Thread selected:", threadId);
  // Implement thread switching
};

const handleWorkspaceSelect = (workspaceId: string) => {
  console.log("Workspace selected:", workspaceId);
  // Implement workspace switching
};

// Demo controls
const addStreamingMessage = () => {
  isLoading.value = true;

  setTimeout(() => {
    const streamingMessage: Message = {
      id: `streaming-${Date.now()}`,
      role: "assistant",
      content:
        "This is a simulated streaming response that demonstrates how the typing indicator works and how messages appear in real-time.",
      timestamp: new Date(),
      isStreaming: true,
    };

    messages.value.push(streamingMessage);
    isLoading.value = false;
  }, 3000);
};

const clearChat = () => {
  messages.value = [];
};
</script>

<template>
  <div class="h-screen">
    <!-- Demo Header -->
    <div class="bg-muted/50 border-b p-4">
      <div class="max-w-7xl mx-auto flex items-center justify-between">
        <div>
          <h1 class="text-2xl font-bold">Chat Interface Demo</h1>
          <p class="text-sm text-muted-foreground">
            Complete chat interface with sidebar, messages, and input
          </p>
        </div>

        <div class="flex items-center gap-2">
          <UiButton
            variant="outline"
            size="sm"
            :disabled="isLoading"
            @click="addStreamingMessage"
          >
            <Icon name="lucide:plus" class="w-4 h-4 mr-1" />
            Add Streaming Message
          </UiButton>

          <UiButton variant="outline" size="sm" @click="clearChat">
            <Icon name="lucide:trash-2" class="w-4 h-4 mr-1" />
            Clear Chat
          </UiButton>
        </div>
      </div>
    </div>

    <!-- Chat Container -->
    <div class="h-[calc(100vh-5rem)]">
      <ChatContainer
        :messages="messages"
        :is-loading="isLoading"
        :current-thread="currentThread"
        @message-submit="handleMessageSubmit"
        @message-copy="handleMessageCopy"
        @message-edit="handleMessageEdit"
        @message-delete="handleMessageDelete"
        @message-regenerate="handleMessageRegenerate"
        @source-click="handleSourceClick"
        @thread-select="handleThreadSelect"
        @workspace-select="handleWorkspaceSelect"
      />
    </div>
  </div>
</template>
